using System.Reflection;
[assembly: AssemblyTitle("CxFinder")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("CxFinder")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2015-2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.1.*")]
