using System.Reflection;
[assembly: AssemblyTitle("AdsRemote")]
[assembly: AssemblyDescription("Automation interface for TwinCAT.Ads API")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("AdsRemote")]
[assembly: AssemblyCopyright("Copyright © Nikolai Voronin 2013-2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.5.*")]
